/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:17b2fcc7-11a3-40ce-b75c-ee74180f9442",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sy1tuWR20",
    "aws_user_pools_web_client_id": "4bp4sc668al9mfusl8hbcfkrhi",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dfytlmbd2rabtaa2ehpimsklvi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
